#!/bin/bash
#
# Install Magento Script
#
# install_magento DATABASE_NAME URL
#

# Check Command
if [ -z "$2" ]; then
    echo "$0 DATABASE_NAME URL"
    exit 1
fi

# Create Database
echo "<?php \
    \$conn = new PDO('mysql:host=db', 'root', 'magento'); \
    \$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION); \
    \$conn->exec('CREATE DATABASE IF NOT EXISTS $1'); \
    " | php

# Install magento
php bin/magento setup:install --use-rewrites=1 \
    --db-host=db \
    --db-name=$1 \
    --db-user=root \
    --db-password=magento \
    --db-prefix=m_ \
    --admin-firstname=Admin \
    --admin-lastname=Admin \
    --admin-email=admin@m2.io \
    --admin-user=admin \
    --admin-password=admin123 \
    --base-url=$2 \
    --backend-frontname=admin \
    --admin-use-security-key=0 \
    --key=8f1e9249ca82c072122ae8d08bc0b0cf

# Update config for testing
#php bin/magento config:set cms/wysiwyg/enabled disabled
#php bin/magento config:set admin/security/admin_account_sharing 1
#php bin/magento config:set admin/captcha/enable 0
